# Generated by Django 5.1.1 on 2024-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Статус публикации продукта",
                verbose_name="Опубликовано",
            ),
        ),
    ]
