# Generated by Django 5.1.1 on 2024-10-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_is_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="version",
            old_name="version_sign",
            new_name="is_current",
        ),
    ]
